development:
  adapter: postgresql
  encoding: unicode
  database: huemorme_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: huemorme_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: huemorme_production
  pool: 5
